from .unit_client_tests import *
from .unit_coach_tests import *
from .unit_group_tests import *
from .unit_payment_tests import *
from .unit_training_tests import *
from .selenium_client_test import *
from .selenium_coach_test import *
from .selenium_group_test import *
from .selenium_payment_test import *
from .selenium_training_test import *
