# Generated by Django 4.1.7 on 2023-04-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_alter_coach_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='telegram_name',
        ),
        migrations.AddField(
            model_name='client',
            name='telegram_id',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Telegram'),
            preserve_default=False,
        ),
    ]
