# Generated by Django 4.1.7 on 2023-04-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_remove_client_telegram_name_client_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='telegram_name',
        ),
        migrations.AddField(
            model_name='coach',
            name='telegram_id',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Telegram'),
            preserve_default=False,
        ),
    ]
