# Generated by Django 4.1.7 on 2023-04-19 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_remove_client_payment_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LazyDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала заморозки')),
                ('end_date', models.DateField(verbose_name='Дата окончания заморозки')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lazy_days', to='webapp.payment')),
            ],
        ),
    ]
