# Generated by Django 4.1.7 on 2023-04-21 09:23

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):
    dependencies = [
        ('webapp', '0025_lazydays'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
