# Generated by Django 4.1.7 on 2023-05-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_auto_20230421_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('owner', 'owner'), ('manager', 'manager')]},
        ),
        migrations.AlterModelOptions(
            name='coach',
            options={'permissions': [('owner', 'owner'), ('manager', 'manager')]},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'permissions': [('owner', 'owner'), ('manager', 'manager')]},
        ),
        migrations.AlterModelOptions(
            name='grouptraining',
            options={'permissions': [('owner', 'owner'), ('manager', 'manager')]},
        ),
        migrations.AlterModelOptions(
            name='lazydays',
            options={'permissions': [('owner', 'owner'), ('manager', 'manager')]},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'permissions': [('owner', 'owner'), ('manager', 'manager')]},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'permissions': [('owner', 'owner'), ('manager', 'manager')]},
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_end_date',
            field=models.DateField(verbose_name='Дата окончания абонемента'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_start_date',
            field=models.DateField(verbose_name='Дата начала абонемента'),
        ),
    ]
